# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssG3H7e00Lbd1rwJxNoD80nGEZBll2Ue
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import gzip
from statsmodels.tsa.arima.model import ARIMA

st.title("📈 Groundwater Forecasting (ARIMA Model)")

uploaded_file = st.file_uploader("Upload CSV with 'Date' and 'Actual_Depth'", type=['csv'])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
    df.sort_index(inplace=True)

    st.subheader("📊 Input Time Series Plot")
    st.line_chart(df['Actual_Depth'])

    # Load the model
    with gzip.open('/content/arima_model (2).pkl.gz', 'rb') as f:
        model = pickle.load(f)

    # Forecast
    steps = st.slider("How many future days to forecast?", 7, 60, 30)
    forecast = model.get_forecast(steps=steps)
    forecast_values = forecast.predicted_mean
    conf_int = forecast.conf_int()

    forecast_df = pd.DataFrame({
        'Forecast': forecast_values,
        'Lower CI': conf_int.iloc[:, 0],
        'Upper CI': conf_int.iloc[:, 1]
    })
    forecast_df.index = pd.date_range(start=df.index[-1] + pd.Timedelta(days=1), periods=steps)

    st.subheader("📉 Forecast Plot")
    st.line_chart(forecast_df[['Forecast']])

    st.subheader("🔍 Forecast Table")
    st.dataframe(forecast_df.round(3))